#启用指定的 profiles
Debug: true
spring:
  profiles:
    active: local

---
#本机开发环境.

spring:
   profiles: local
   datasource:
      name: druid
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/ims?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: abcd1234
      driver-class-name: com.mysql.jdbc.Driver

#mybatis mapper 配置.
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


#服务端口.
server:
  port: 7777

multipart:
  enabled: true

#日志路径和名称配置.
logging:
  file: demo
  path: D://logs

